import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Nav from "../components/Nav/Nav";

export default function Home() {
  return (

    <div className={styles.container}>
      <Head>
        <title>Kuvars Mühendislik</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <Nav/>



      </main>

      <footer >

      </footer>
    </div>
  )
}
